name: Publish release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    name: Package
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Read extension version
        id: ext-version
        run: |
          content=`cat ./package.json | jq -r .version`
          echo "::set-output name=content::$content"
      - name: Ensure version matches with tag
        if: ${{ github.ref != format('refs/tags/v{0}', steps.ext-version.outputs.content) }}
        run: |
          echo "Version mismatch!"
          echo "Received ref: ${{ github.ref }}"
          echo "Expected ref: refs/tags/v${{ steps.ext-version.outputs.content }}"
          exit 1
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm run package
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          path: "*.vsix"

  publish:
    name: Publish All
    runs-on: ubuntu-latest
    needs: build
    if: success() && startsWith( github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
      - run: npx vsce publish --no-git-tag-version --packagePath $(find . -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
